CREATE DATABASE IF NOT EXISTS biblonexa CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE biblonexa;
CREATE TABLE IF NOT EXISTS usuarios (
 id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 nombre VARCHAR(100) NOT NULL,
 correo VARCHAR(150) NOT NULL UNIQUE,
 contrasena VARCHAR(255) NOT NULL,
 fecha_registro TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS materiales (
 id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 titulo VARCHAR(150) NOT NULL,
 categoria VARCHAR(100) NOT NULL,
 nombre_original VARCHAR(255) NOT NULL,
 nombre_archivo VARCHAR(255) NOT NULL UNIQUE,
 ruta_archivo VARCHAR(500) NOT NULL,
 usuario_id INT UNSIGNED NULL,
 fecha_subida TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 FOREIGN KEY (usuario_id) REFERENCES usuarios(id) ON DELETE SET NULL
) ENGINE=InnoDB;
